# use_frameworks!

platform :ios, '11.0'

target 'LLAdMob_Example' do
  
  pod 'MBProgressHUD', '~> 1.2.0'
  
  pod 'LLAdMob', :path => '../'

  target 'LLAdMob_Tests' do
    inherit! :search_paths

    
  end
end
